##########################################
###        TOKEN TEST
########################################## 
### 1 - BGPDATA FETCH WITHOUT TOKEN
GET http://192.168.20.30:8000/bgpmap/asn/174/?token=2017 HTTP/1.1
###### Wed Oct 25 03:04:02 PDT 2017 Test OK - Ryan

##########################################  
###        AS DETAILS
########################################## 
### 2 - AS Detail by ASN (Unique return)35
GET http://192.168.20.30:8000/bgpmap/asn/139/?token=2017 HTTP/1.1
###### Wed Oct 25 03:04:36 PDT 2017 Test OK - Ryan

### 3 - AS Detail by description (with limit and specical symbols)
GET http://192.168.20.30:8000/bgpmap/desc/Homeland Security/?token=2017&limit=100 HTTP/1.1
###### Thu Oct 26 01:06:26 PDT 2017 Test OK - Ryan

### 4 - AS Detail by Address (with limit)
GET http://192.168.20.30:8000/bgpmap/address/University of Hong Kong/?token=2017&limit=20 HTTP/1.1
###### Thu Oct 26 01:06:17 PDT 2017 Test OK - Ryan

##########################################  
###        PREFIX QUERY
########################################## 
### 5 - AS Prefix search by ASN
GET http://192.168.20.30:8000/bgpmap/prefix/335/?token=ardsec-201710 HTTP/1.1
###### Thu Oct 26 00:45:49 PDT 2017 Test OK - Ryan

### 6 - AS Prefix search by IP address (IP ONLY)
GET http://192.168.20.30:8000/bgpmap/prefix/148.0.0.0/?token=2017 HTTP/1.1
###### Thu Oct 26 00:47:49 PDT 2017 Test OK - Ryan

### 7 - AS Prefix search by IP address (IP /cidr)
GET http://192.168.20.30:8000/bgpmap/prefix/148.0.0.0/?token=2017&cidr=16 HTTP/1.1
###### Thu Oct 26 00:58:12 PDT 2017 Test OK - Ryan

########################################## 
###        PATH OF BGP
########################################## 
### 8 - Upstream Query by ASN
GET http://192.168.20.30:8000/bgpmap/upstream/1/?token=2017 HTTP/1.1
###### Thu Oct 26 02:48:44 PDT 2017 Test OK - Ryan

### 9 - Downstream Query by ASN
GET http://192.168.20.30:8000/bgpmap/downstream/1/?token=ardsec-201710 HTTP/1.1
###### Thu Oct 26 03:01:51 PDT 2017 Test OK - Ryan

### 10 - Relation Path by ASN
GET http://192.168.20.30:8000/bgpmap/aggre/123/?token=ardsec-201710 HTTP/1.1
###### Thu Oct 26 20:18:50 PDT 2017 Test OK - Ryan


##########################################
###         NHSP
###    - Next Hop Static Prediction
########################################## 
### 12 - Prediction AS 1 to AS 7018 (simple query)
GET http://192.168.20.30:8000/bgpmap/nhsp/?token=ardsec-201710&from=1&to=7019

### 13 - Prediction 222.18.0.0 to 8.8.8.8 ( Query Prefix of ASN, try /24 /16 /8 ? ,then Call #12)
GET http://192.168.20.30:8000/bgpmap/nhsp/?token=ardsec-201710&from=1&to=7019

### 14 - Prediction `University of Hong Kong` to `Homeland Security(US)` ( Query ASN Details, Call #12)
GET http://192.168.20.30:8000/bgpmap/nhsp/?token=ardsec-201710&from=1&to=7019

##########################################
###         VISUALIZATION
########################################## 
### 11 - Path visualization data sendback, query by asn (nodes&links)
GET http://192.168.20.30:8000/bgpmap/viz/1/?token=ardsec-201710 HTTP/1.1
# Get ROUTING
GET http://192.168.20.30:8000/bgpmap/traffic/?token=2017&info=asn&src=1&dst=174&type=json HTTP/1.1

########################################## 
###        DATA VERSION DETIALS
########################################## 
### 15 - Data Version
GET http://192.168.20.30:8000/bgpmap/version/?token=2017 HTTP/1.1
###### Thu Oct 26 00:58:47 PDT 2017 Test OK - Ryan


########################################## 
###       Devices DETIALS
########################################## 
### 16 - Device Details
GET http://192.168.20.30:8000/devices/name/NWTSGB-1-LRE01/?token=2017 HTTP/1.1
###### Thu Dec 19 00:58:47 PDT 2017 Test OK - Ryan
### 17 - Device Links
GET http://192.168.20.30:8000/devices/links/NWTSGB-1-LRE01/?token=2017 HTTP/1.1
###### Thu Dec 19 00:58:47 PDT 2017 Test OK - Ryan





#######
#    IN produce
#######

# 1. Get ASN by user search input
## 1.1 If input Address
GET http://192.168.20.30:8000/bgpmap/address/University of Hong Kong/?token=2017 HTTP/1.1
#########################

# 2. Get BGPMAP by ASN 3661
GET http://192.168.20.30:8000/bgpmap/vis/3661/?token=2017&type=json HTTP/1.1
##########################

# 3. Request 3661 Details
### 1 - BGPDATA FETCH WITHOUT TOKEN
GET http://192.168.20.30:8000/bgpmap/asn/3661/?token=2017 HTTP/1.1
##########################